version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g typescript
  build:
    commands:
      - cd core && npm install && tsc
      - cd lambdas && npm install && tsc
      - cd mongo && npm install && tsc
      - aws cloudformation package --debug --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - aws cloudformation package --debug --template lambdas/template.yml --s3-bucket $S3_BUCKET --output-template template-lambdas.yml
      - aws cloudformation package --debug --template mongo/template.yml --s3-bucket $S3_BUCKET --output-template template-mongo.yml
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  type: zip
  files:
    - template-export.yml
    - template-lambdas.yml
    - template-mongo.yml
