AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  UserListQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      FifoQueue: true
      MessageRetentionPeriod: 600

#  GetHelloWorld:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: index.get
#      Runtime: nodejs6.10
#      Role:
#        Fn::ImportValue:
#          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
#      Events:
#        GetEvent:
#          Type: Api
#          Properties:
#            Path: /
#            Method: get

  UserListFromPastebin:
    Type: AWS::Serverless::Function
    Properties:
      Handler: users.readFromPastebin
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
    Environment: {
      Variables: {
        QUEUE_URL: { "Fn::GetAtt": ["UserListQueue", "QueueUrl"] },
        REGION: { "Ref", "AWS::Region" }
      }
    }

  UserListToMongo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: users.writeToDB
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
    Environment: {
      Variables: {
        QUEUE_URL: { "Fn::GetAtt": ["UserListQueue", "QueueUrl"] },
        REGION: { "Ref", "AWS::Region" }
      }
    }
